# Generated by Django 5.1.1 on 2024-10-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_word_updated_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Joint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "words",
                    models.ManyToManyField(related_name="joints", to="game.word"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
