# Generated by Django 5.1.1 on 2024-10-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_exercise"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joint",
            name="is_public",
        ),
    ]
