# Generated by Django 5.1.1 on 2024-10-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("Principal", "Principal"),
                    ("Teacher", "Teacher"),
                    ("Student", "Student"),
                ],
                max_length=15,
            ),
        ),
    ]
