# Generated by Django 4.2.12 on 2024-09-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palavra",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
